# fly.toml file generated for jw-reports-notifications-server on 2023-02-16T23:13:58-06:00

app = "jw-reports-notifications-server"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  SUPABASE_URL = "https://jtwyabqdnaxsdjpglrek.supabase.co"
  SUPABASE_APY_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0d3lhYnFkbmF4c2RqcGdscmVrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY2MzEyODg3MSwiZXhwIjoxOTc4NzA0ODcxfQ.Srnvfk452ObK2f72fHrOu9Tto6ggwbXRNkod1qSrBY4"
  ONESIGNAL_APP_ID = "9de35a86-0436-4213-b4aa-c28770cea586"
  ONESIGNAL_REST_API_KEY = "NmM2NzdmOWYtZDcxYy00NWU2LWI3NDctYmFhYWJlOTg5Yjgz"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
